app = "kali-fly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  DEBIAN_FRONTEND = "noninteractive"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Optional if you need custom SSH or TCP access on another port:
# [[services]]
#   internal_port = 2222
#   protocol = "tcp"
#   [[services.ports]]
#     port = 2222

[vm]
  size = "shared-cpu-1x"
